# repos:
# - repo: https://github.com/kynan/nbstripout
#   rev: 0.3.9
#   hooks:
#     - id: nbstripout
# - repo: https://github.com/Quantco/pre-commit-mirrors-black
#   rev: 20.8b1
#   hooks:
#     - id: black-conda
#       args:
#         - --safe
#         - --target-version=py36
# - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
#   rev: v3.8.4
#   hooks:
#    - id: flake8-conda
#      additional_dependencies: [flake8-docstrings, flake8-rst-docstrings]
# - repo: https://github.com/Quantco/pre-commit-mirrors-isort
#   rev: 5.6.4
#   hooks:
#    - id: isort-conda
#      additional_dependencies: [toml]
# - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
#   rev: "0.790"
#   hooks:
#    - id: mypy-conda
# - repo: https://github.com/Quantco/pre-commit-mirrors-pyupgrade
#   rev: 2.7.2
#   hooks:
#    - id: pyupgrade-conda
